const baseDays=[
 {name:'Lunes',focus:'Fuerza completa',desc:'Empieza la semana con energía, sin agotarte.',groups:{'MAÑANA':['Vaso de agua al levantarte','Movilidad suave · 5 min'],'ENTRENAMIENTO · 30–40 MIN':['Sentadilla con mancuerna · 3×10','Flexiones · 3 series cómodas','Remo con mancuerna o goma · 3×12','Plancha · 3×30 s'],'HÁBITOS':['Desayuno salado y proteico','Caminar al menos 20 min','Preparar comida del martes','Acostarte sobre las 22:00']}},
 {name:'Martes',focus:'Tren superior',desc:'Trabajo breve de fuerza y buena postura.',groups:{'MAÑANA':['Vaso de agua al levantarte','Movilidad de hombros · 5 min'],'ENTRENAMIENTO · 30–40 MIN':['Press de hombro con mancuernas · 3×10','Dominadas asistidas o remo con goma · 3×8–12','Flexiones inclinadas · 3×10','Curl de bíceps con goma · 3×12'],'HÁBITOS':['Desayuno salado y proteico','Pausa activa a media mañana','Caminar al menos 20 min','Dejar lista la ropa de correr']}},
 {name:'Miércoles',focus:'Día de carrera',desc:'Ritmo cómodo: debes poder mantener una conversación.',groups:{'MAÑANA':['Vaso de agua al levantarte','Activación de tobillos y cadera · 5 min'],'ENTRENAMIENTO · 30–40 MIN':['Calentar caminando · 5 min','Correr suave · 20–25 min','Caminar y estirar · 5 min'],'BATCH COOKING':['Cocinar base para jueves y viernes','Preparar arroz, legumbre o verduras','Dejar 2 raciones listas'],'HÁBITOS':['Hidratación después de correr','Acostarte sobre las 22:00']}},
 {name:'Jueves',focus:'Piernas y core',desc:'Fuerza controlada para reforzar todo el cuerpo.',groups:{'MAÑANA':['Vaso de agua al levantarte','Movilidad suave · 5 min'],'ENTRENAMIENTO · 30–40 MIN':['Zancadas o split squat · 3×8 por lado','Peso muerto rumano con mancuernas · 3×10','Puente de glúteos · 3×15','Dead bug · 3×8 por lado'],'HÁBITOS':['Desayuno salado y proteico','Caminar al menos 20 min','Preparar bolsa del gimnasio','Evitar cafeína por la tarde']}},
 {name:'Viernes',focus:'Gimnasio del club',desc:'Máquinas, técnica limpia y esfuerzo moderado.',groups:{'MAÑANA':['Vaso de agua al levantarte','Movilidad general · 5 min'],'GIMNASIO · 35–40 MIN':['Prensa de piernas · 3×10','Jalón al pecho · 3×10','Press de pecho · 3×10','Remo sentado · 3×10','Vuelta a la calma · 5 min'],'HÁBITOS':['Desayuno salado y proteico','Caminar un rato al aire libre','Cena sencilla y equilibrada']}},
 {name:'Sábado',focus:'Movimiento sin presión',desc:'Actividad suave para recuperarte y mantener el hábito.',groups:{'ACTIVIDAD':['Paseo largo, bici o juego activo · 30–40 min','Movilidad o estiramientos · 10 min'],'HÁBITOS':['Beber agua con regularidad','Comer fruta y verdura','Disfrutar sin buscar perfección','Revisar qué falta para la compra']}},
 {name:'Domingo',focus:'Preparar la semana',desc:'Un poco de movimiento y organización para ponértelo fácil.',groups:{'ACTIVIDAD SUAVE':['Paseo tranquilo · 30 min','Movilidad · 10 min'],'BATCH COOKING':['Planificar menú semanal','Hacer la compra','Cocer arroz o cereal base','Preparar legumbres, verduras y proteína','Guardar raciones para lunes–miércoles'],'CIERRE DEL DÍA':['Preparar ropa y bolsa del lunes','Revisar la semana en la app','Acostarte sobre las 22:00']}}
];
const key='rutina-javi-v1'; let custom=JSON.parse(localStorage.getItem(key+'-custom')||'null')||{}; let checks=JSON.parse(localStorage.getItem(key+'-checks')||'{}');
const jsDay=(new Date().getDay()+6)%7; let selected=jsDay;
const $=s=>document.querySelector(s); const nav=$('#dayNav');
function dayData(i){const d=structuredClone(baseDays[i]); if(custom[i]) d.groups=custom[i]; if(!d.groups['MEDICACIÓN']) d.groups={'MEDICACIÓN':['21:00 · Tomar medicación'],...d.groups}; return d}
function dateFor(i){const d=new Date();d.setDate(d.getDate()+i-jsDay);return d}
function idFor(i,g,t){return `${dateFor(i).toISOString().slice(0,10)}|${g}|${t}`}
function render(){const d=dayData(selected),date=dateFor(selected);$('#dayTitle').textContent=d.name;$('#dateLabel').textContent=date.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});$('#focusTitle').textContent=d.focus;$('#focusText').textContent=d.desc;
 nav.innerHTML=baseDays.map((x,i)=>`<button data-day="${i}" class="${i===selected?'active':''}">${x.name.slice(0,3)}<small>${dateFor(i).getDate()}</small></button>`).join('');
 let total=0,done=0; const root=$('#taskGroups');root.innerHTML=''; Object.entries(d.groups).forEach(([g,tasks])=>{const sec=document.createElement('section');sec.className='group';sec.innerHTML=`<h3>${g}</h3>`;tasks.forEach(t=>{total++;const id=idFor(selected,g,t),on=!!checks[id];if(on)done++;const label=document.createElement('label');label.className='task';label.innerHTML=`<input type="checkbox" ${on?'checked':''}><i class="check"></i><span></span>`;label.querySelector('span').textContent=t;label.querySelector('input').onchange=e=>{checks[id]=e.target.checked;localStorage.setItem(key+'-checks',JSON.stringify(checks));renderProgress()};sec.append(label)});root.append(sec)});renderProgress();
 function renderProgress(){const inputs=[...document.querySelectorAll('.task input')];const n=inputs.filter(x=>x.checked).length;$('#progressText').textContent=`${n}/${inputs.length}`;$('#progressBar').style.width=`${inputs.length?n/inputs.length*100:0}%`}
}
nav.onclick=e=>{const b=e.target.closest('button[data-day]');if(b){selected=+b.dataset.day;render()}};$('#todayBtn').onclick=()=>{selected=jsDay;render()};
$('#editBtn').onclick=()=>{const d=dayData(selected),box=$('#editFields');box.innerHTML='';Object.entries(d.groups).forEach(([g,t])=>{const div=document.createElement('div');div.className='field';div.innerHTML=`<label></label><textarea></textarea>`;div.querySelector('label').textContent=g;div.querySelector('textarea').value=t.join('\n');div.querySelector('textarea').dataset.group=g;box.append(div)});$('#editDialog').showModal()};
$('#saveBtn').onclick=e=>{e.preventDefault();const obj={};document.querySelectorAll('#editFields textarea').forEach(x=>obj[x.dataset.group]=x.value.split('\n').map(s=>s.trim()).filter(Boolean));custom[selected]=obj;localStorage.setItem(key+'-custom',JSON.stringify(custom));$('#editDialog').close();render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
